/**
 * Country phrase → exact `countries.name` for AI library search (54 AU member states + common exonyms).
 * Longest phrase wins in {@link resolveCountryFromMultilingualQuery}.
 */

/** Canonical DB names used across Yamalé (align with `countries.name`). */
export const AFRICAN_COUNTRY_DB_NAMES = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Congo Republic",
  "DR Congo",
  "Côte d'Ivoire",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "São Tomé and Príncipe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
] as const;

const FRENCH_COUNTRY_PHRASES: Readonly<Record<string, string>> = {
  algerie: "Algeria",
  angola: "Angola",
  benin: "Benin",
  botswana: "Botswana",
  "burkina faso": "Burkina Faso",
  burundi: "Burundi",
  "cap vert": "Cabo Verde",
  "cabo verde": "Cabo Verde",
  cameroun: "Cameroon",
  "republique centrafricaine": "Central African Republic",
  "centrafrique": "Central African Republic",
  tchad: "Chad",
  comores: "Comoros",
  "congo brazzaville": "Congo Republic",
  "republique du congo": "Congo Republic",
  "republique democratique du congo": "DR Congo",
  "rd congo": "DR Congo",
  "rdc": "DR Congo",
  "congo kinshasa": "DR Congo",
  "cote d ivoire": "Côte d'Ivoire",
  "cote divoire": "Côte d'Ivoire",
  "ivoire coast": "Côte d'Ivoire",
  djibouti: "Djibouti",
  egypte: "Egypt",
  "guinee equatoriale": "Equatorial Guinea",
  erythree: "Eritrea",
  eswatini: "Eswatini",
  swaziland: "Eswatini",
  ethiopie: "Ethiopia",
  gabon: "Gabon",
  gambie: "Gambia",
  ghana: "Ghana",
  guinee: "Guinea",
  "guinee bissau": "Guinea-Bissau",
  kenya: "Kenya",
  lesotho: "Lesotho",
  liberia: "Liberia",
  libye: "Libya",
  madagascar: "Madagascar",
  malawi: "Malawi",
  mali: "Mali",
  mauritanie: "Mauritania",
  maurice: "Mauritius",
  maroc: "Morocco",
  mozambique: "Mozambique",
  namibie: "Namibia",
  niger: "Niger",
  nigeria: "Nigeria",
  rwanda: "Rwanda",
  "sao tome": "São Tomé and Príncipe",
  "sao tome et principe": "São Tomé and Príncipe",
  senegal: "Senegal",
  seychelles: "Seychelles",
  "sierra leone": "Sierra Leone",
  somalie: "Somalia",
  "afrique du sud": "South Africa",
  "soudan du sud": "South Sudan",
  soudan: "Sudan",
  tanzanie: "Tanzania",
  togo: "Togo",
  tunisie: "Tunisia",
  ouganda: "Uganda",
  zambie: "Zambia",
  zimbabwe: "Zimbabwe",
};

const ARABIC_COUNTRY_PHRASES: Readonly<Record<string, string>> = {
  الجزائر: "Algeria",
  أنغولا: "Angola",
  انغولا: "Angola",
  بنين: "Benin",
  بوتسوانا: "Botswana",
  "بوركينا فاسو": "Burkina Faso",
  بوروندي: "Burundi",
  "الرأس الأخضر": "Cabo Verde",
  الكاميرون: "Cameroon",
  "جمهورية أفريقيا الوسطى": "Central African Republic",
  تشاد: "Chad",
  "جزر القمر": "Comoros",
  "الكونغو برازافيل": "Congo Republic",
  "الكونغو الديمقراطية": "DR Congo",
  "ساحل العاج": "Côte d'Ivoire",
  "كوت ديفوار": "Côte d'Ivoire",
  جيبوتي: "Djibouti",
  مصر: "Egypt",
  "غينيا الاستوائية": "Equatorial Guinea",
  إريتريا: "Eritrea",
  اريتريا: "Eritrea",
  إسواتيني: "Eswatini",
  اثيوبيا: "Ethiopia",
  إثيوبيا: "Ethiopia",
  الغابون: "Gabon",
  غامبيا: "Gambia",
  غانا: "Ghana",
  غينيا: "Guinea",
  "غينيا بيساو": "Guinea-Bissau",
  كينيا: "Kenya",
  ليسوتو: "Lesotho",
  ليبيريا: "Liberia",
  ليبيا: "Libya",
  مدغشقر: "Madagascar",
  ملاوي: "Malawi",
  مالي: "Mali",
  موريتانيا: "Mauritania",
  موريشيوس: "Mauritius",
  المغرب: "Morocco",
  موزمبيق: "Mozambique",
  ناميبيا: "Namibia",
  النيجر: "Niger",
  نيجيريا: "Nigeria",
  رواندا: "Rwanda",
  "ساو تومي وبرينسيب": "São Tomé and Príncipe",
  السنغال: "Senegal",
  سيشل: "Seychelles",
  "سيراليون": "Sierra Leone",
  الصومال: "Somalia",
  "جنوب افريقيا": "South Africa",
  "جنوب أفريقيا": "South Africa",
  "جنوب السودان": "South Sudan",
  السودان: "Sudan",
  تنزانيا: "Tanzania",
  توغو: "Togo",
  تونس: "Tunisia",
  أوغندا: "Uganda",
  اوغندا: "Uganda",
  زامبيا: "Zambia",
  زيمبابوي: "Zimbabwe",
};

const ENGLISH_EXONYMS: Readonly<Record<string, string>> = {
  "ivory coast": "Côte d'Ivoire",
  "cape verde": "Cabo Verde",
  "drc": "DR Congo",
  "dr congo": "DR Congo",
  "democratic republic of congo": "DR Congo",
  "democratic republic of the congo": "DR Congo",
  "congo kinshasa": "DR Congo",
  "congo brazzaville": "Congo Republic",
  "republic of the congo": "Congo Republic",
  "central african republic": "Central African Republic",
  "car": "Central African Republic",
  "south sudan": "South Sudan",
  "sao tome and principe": "São Tomé and Príncipe",
  "são tome and príncipe": "São Tomé and Príncipe",
  swaziland: "Eswatini",
  "equatorial guinea": "Equatorial Guinea",
  "guinea bissau": "Guinea-Bissau",
  "guinea-bissau": "Guinea-Bissau",
  "sierra leone": "Sierra Leone",
  "south africa": "South Africa",
  "burkina faso": "Burkina Faso",
};

function buildPhraseMap(): Readonly<Record<string, string>> {
  const out: Record<string, string> = {};

  for (const name of AFRICAN_COUNTRY_DB_NAMES) {
    out[name.toLowerCase()] = name;
  }

  Object.assign(out, ENGLISH_EXONYMS);
  Object.assign(out, FRENCH_COUNTRY_PHRASES);
  Object.assign(out, ARABIC_COUNTRY_PHRASES);

  return out;
}

export const AFRICAN_COUNTRY_SEARCH_PHRASES: Readonly<Record<string, string>> = buildPhraseMap();
